version: "3"

services:
  gotenberg:
    image: 'gotenberg/gotenberg:7'
    build:
      dockerfile: ./gotenberg/Dockerfile
    healthcheck:
      test: [ "CMD", "curl", "-f",  "http://localhost:3000/health" ]
      retries: 3
      timeout: 5s
    ports:
      - '3000:3000'
    restart: always
